// Auto-generated by `ai-memory install-hooks --agent pi --apply`.
// Edit by re-running the command, not by hand — install-hooks
// will overwrite this file (with a `.bak-<ts>` backup) on each
// re-run.

import { execFileSync } from "node:child_process";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync as readMarkerText, readSync, readdirSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve, sep } from "node:path";
import { homedir } from "node:os";

const SERVER = "http://127.0.0.1:49374".replace(/\/+$/, "");
const AGENT = "pi";
const TOKEN: string | null = null;

// capture-policy-v1 (generated; do not fork between adapters)
const CAPTURE_POLICY_V1 = 1;
const CAPTURE_MARKER_MAX_BYTES = 64 * 1024;
const CAPTURE_MAX_PATTERNS = 128;
const CAPTURE_MAX_PATTERN_CHARS = 1024;
const CAPTURE_MAX_PATH_CHARS = 4096;
const CAPTURE_MAX_CANDIDATES = 32;
const CAPTURE_MAX_WORK = 1000000;
const CAPTURE_MAX_CALL_ID_CHARS = 128;

type CaptureDisposition = "keep" | "drop" | "metadata-only";
type CaptureProtocol = { version: 1; disposition: CaptureDisposition; policy_state: "inactive" | "active" | "invalid"; tool_family: "file" | "search-list" | "non-file" | "unknown"; path_count: number; extraction_state: "not-applicable" | "extracted" | "missing-or-malformed" | "unsupported-schema" };

type CaptureConfig = { state: "inactive" | "active" | "invalid"; patterns: { path: string; windows: boolean; directory?: string }[]; base: string };
function readFileSync(path: string, encoding?: "utf8"): any { if (encoding) return readMarkerText(path, encoding); const fd = openSync(path, "r"); try { const bytes = Buffer.allocUnsafe(CAPTURE_MARKER_MAX_BYTES + 1); const count = readSync(fd, bytes, 0, bytes.length, 0); if (count > CAPTURE_MARKER_MAX_BYTES) throw new Error("marker too large"); const result = bytes.subarray(0, count); new TextDecoder("utf-8", { fatal: true }).decode(result); return result; } finally { closeSync(fd); } }
function captureTrimComment(line: string): string { let quote = ""; let escaped = false; for (let i = 0; i < line.length; i++) { const c = line[i]; if (escaped) { escaped = false; continue; } if (c === "\\" && quote === '"') { escaped = true; continue; } if ((c === '"' || c === "'") && (!quote || quote === c)) quote = quote ? "" : c; else if (c === "#" && !quote) { line = line.slice(0, i); break; } } if (line.trimStart().startsWith("[") && !/^\s*\[[^\]]+\]\s*$/.test(line)) throw new Error("invalid table header"); if (quote) throw new Error("unterminated string"); return line; }
function captureNormalize(path: string): { path: string; windows: boolean } | undefined { const p = path.replace(/\\/g, "/"); let root: string; let tail: string[]; if (p.startsWith("//")) { const x = p.slice(2).split("/").filter(Boolean); if (x.length < 2) return undefined; root = `//${x.shift()}/${x.shift()}`; tail = x; } else if (/^[A-Za-z]:\//.test(p)) { root = `${p[0].toUpperCase()}:/`; tail = p.slice(3).split("/"); } else if (p.startsWith("/")) { root = "/"; tail = p.slice(1).split("/"); } else return undefined; const out: string[] = []; for (const x of tail) { if (!x || x === ".") continue; if (x === "..") out.pop(); else out.push(x); } return { path: root + (out.length ? (root.endsWith("/") ? "" : "/") + out.join("/") : ""), windows: root !== "/" }; }
function captureJoin(base: string, child: string): string { if (/^[^A-Za-z]?:|^[A-Za-z]:[^/\\]/.test(child)) return child; return `${base.replace(/[\\/]+$/, "")}/${child}`; }
function captureValidGlob(p: string): boolean {
  if (!p) return false;
  if ([...p].length > CAPTURE_MAX_PATTERN_CHARS) return false;
  if (/[!{}\[\]()|^$%]/.test(p)) return false;
  if (p.includes("${")) return false;
  if (p.includes("***")) return false;
  if (p.replace(/\\/g, "/").split("/").includes("..")) return false;
  if (p.startsWith("~") && !p.startsWith("~/")) return false;
  if (/^[^A-Za-z]?:/.test(p)) return false;
  return !/^[A-Za-z]:[^/\\]/.test(p);
}
type CaptureScanner = { value: string; i: number };
const CAPTURE_BASIC_ESCAPES: Record<string, string> = { b: "\b", t: "\t", n: "\n", f: "\f", r: "\r", '"': '"', "\\": "\\" };
function captureSkipSpace(s: CaptureScanner): void { while (/\s/.test(s.value[s.i] ?? "")) s.i++; }
function captureUnicodeEscape(s: CaptureScanner, kind: string): string | undefined {
  const count = kind === "u" ? 4 : 8;
  const hex = s.value.slice(s.i, s.i + count);
  if (!new RegExp(`^[0-9A-Fa-f]{${count}}$`).test(hex)) return undefined;
  const n = Number.parseInt(hex, 16);
  if (n > 0x10ffff) return undefined;
  if (n >= 0xd800 && n <= 0xdfff) return undefined;
  s.i += count;
  return String.fromCodePoint(n);
}
function captureEscape(s: CaptureScanner): string | undefined {
  const e = s.value[s.i++];
  if (e in CAPTURE_BASIC_ESCAPES) return CAPTURE_BASIC_ESCAPES[e];
  if (e === "u" || e === "U") return captureUnicodeEscape(s, e);
  return undefined;
}
// Reads one basic ("...") or literal ('...') TOML string; undefined rejects the array.
function captureParseString(s: CaptureScanner): string | undefined {
  const quote = s.value[s.i++];
  if (quote !== '"' && quote !== "'") return undefined;
  let out = "";
  for (;;) {
    if (s.i >= s.value.length) return undefined;
    const c = s.value[s.i++];
    if (c === quote) return out;
    if (c === "\n" || c === "\r") return undefined;
    if (c !== "\\" || quote !== '"') { out += c; continue; }
    const escaped = captureEscape(s);
    if (escaped === undefined) return undefined;
    out += escaped;
  }
}
function captureParseArray(value: string): string[] | undefined {
  const s: CaptureScanner = { value, i: 0 };
  const out: string[] = [];
  captureSkipSpace(s);
  if (value[s.i++] !== "[") return undefined;
  for (;;) {
    captureSkipSpace(s);
    if (value[s.i] === "]") {
      s.i++;
      captureSkipSpace(s);
      return s.i === value.length ? out : undefined;
    }
    const item = captureParseString(s);
    if (item === undefined) return undefined;
    out.push(item);
    captureSkipSpace(s);
    if (value[s.i] === ",") { s.i++; continue; }
    if (value[s.i] !== "]") return undefined;
  }
}
// Returns ok=false for a malformed [capture] table, or the raw ignore_paths value when present.
function captureScanIgnorePaths(text: string): { ok: boolean; value?: string } {
  let section = "";
  let value = "";
  let collecting = false;
  let seen = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = captureTrimComment(raw).trim();
    if (!line) continue;
    const table = /^\[([^\]]+)\]$/.exec(line);
    if (table) {
      if (collecting) return { ok: false };
      section = table[1];
      continue;
    }
    if (section !== "capture") continue;
    if (seen && !collecting) return { ok: false };
    if (collecting) {
      value += ` ${line}`;
      collecting = !value.includes("]");
      continue;
    }
    const kv = /^([A-Za-z0-9_-]+)\s*=\s*(.*)$/.exec(line);
    if (!kv || kv[1] !== "ignore_paths") return { ok: false };
    seen = true;
    value = kv[2];
    collecting = !value.includes("]");
  }
  if (collecting) return { ok: false };
  return seen ? { ok: true, value } : { ok: true };
}
function captureExpandSource(source: string, home: string, markerBase: string): string {
  if (source.startsWith("~/")) return captureJoin(home, source.slice(2));
  if (/^(?:\/|\\\\|[A-Za-z]:[\\/])/.test(source)) return source;
  return captureJoin(markerBase, source);
}
function capturePattern(source: string, home: string, markerBase: string): CaptureConfig["patterns"][number] | undefined {
  if (!captureValidGlob(source)) return undefined;
  const normalized = captureNormalize(captureExpandSource(source, home, markerBase));
  if (!normalized) return undefined;
  const directory = normalized.path.endsWith("/**") ? (normalized.path.slice(0, -3) || "/") : undefined;
  return { path: normalized.path, windows: normalized.windows, directory };
}
function captureConfig(cwd: string | undefined): CaptureConfig {
  const marker = findMarker(cwd);
  const candidateBase = captureNormalize(cwd ? resolve(cwd) : "")?.path ?? "";
  if (!marker) return { state: "inactive", patterns: [], base: candidateBase };
  try {
    const bytes = readFileSync(marker);
    const markerBase = captureNormalize(dirname(marker))?.path ?? candidateBase;
    if (bytes.byteLength > CAPTURE_MARKER_MAX_BYTES) return { state: "invalid", patterns: [], base: candidateBase };
    const scan = captureScanIgnorePaths(bytes.toString("utf8"));
    if (!scan.ok) return { state: "invalid", patterns: [], base: candidateBase };
    if (scan.value === undefined) return { state: "inactive", patterns: [], base: candidateBase };
    const strings = captureParseArray(scan.value);
    if (!strings || strings.length > CAPTURE_MAX_PATTERNS) return { state: "invalid", patterns: [], base: candidateBase };
    const home = homedir();
    const patterns = strings.map((source) => capturePattern(source, home, markerBase));
    if (patterns.some((p) => !p)) return { state: "invalid", patterns: [], base: candidateBase };
    if (!patterns.length) return { state: "inactive", patterns: [], base: candidateBase };
    return { state: "active", patterns: patterns as CaptureConfig["patterns"], base: candidateBase };
  } catch (_e) {
    return { state: "invalid", patterns: [], base: candidateBase };
  }
}
function captureCharEq(a: string, b: string, insensitive: boolean): boolean {
  if (!insensitive) return a === b;
  if (a.charCodeAt(0) >= 128 || b.charCodeAt(0) >= 128) return a === b;
  return a.toLowerCase() === b.toLowerCase();
}
// A star that precedes another star defers to it; "**" also crosses "/".
function captureGlobStar(p: string[], j: number, ch: string, current: boolean[], previous: boolean[]): boolean {
  if (p[j] === "*") return false;
  if (j >= 2 && p[j - 2] === "*") return current[j - 2] || previous[j];
  if (current[j - 1]) return true;
  return ch !== "/" && previous[j];
}
function captureGlobCell(p: string[], j: number, ch: string, current: boolean[], previous: boolean[], insensitive: boolean): boolean {
  const x = p[j - 1];
  if (x === "*") return captureGlobStar(p, j, ch, current, previous);
  if (x === "?") return ch !== "/" && previous[j - 1];
  return captureCharEq(x, ch, insensitive) && previous[j - 1];
}
function captureGlob(pattern: string, candidate: string, insensitive: boolean, budget: { work: number }): boolean | undefined {
  const p = [...pattern];
  const previous = new Array<boolean>(p.length + 1).fill(false);
  previous[0] = true;
  for (let j = 1; j <= p.length; j++) previous[j] = p[j - 1] === "*" && p[j] !== "*" && previous[j - 1];
  for (const ch of [...candidate]) {
    const current = new Array<boolean>(p.length + 1).fill(false);
    for (let j = 1; j <= p.length; j++) {
      if (++budget.work > CAPTURE_MAX_WORK) return undefined;
      current[j] = captureGlobCell(p, j, ch, current, previous, insensitive);
    }
    for (let j = 0; j <= p.length; j++) previous[j] = current[j];
  }
  return previous[p.length];
}
type CaptureToolInfo = { family: CaptureProtocol["tool_family"]; paths?: string[]; extraction: CaptureProtocol["extraction_state"]; callID?: string };
const CAPTURE_CALL_ID_KEYS = ["tool_use_id", "toolUseId", "tool_call_id", "toolCallId", "call_id", "callId", "callID"];
const CAPTURE_SEARCH_TOOLS = ["search", "grep", "glob", "find", "list", "ls", "list_files", "read_dir"];
const CAPTURE_NON_FILE_TOOLS = ["bash", "shell", "execute", "run_command", "web_search"];
const CAPTURE_FILE_TOOLS = ["read", "write", "edit", "apply_patch", "notebookedit", "notebook_edit", "create_file", "delete_file", "rename_file", "move_file", "multi_edit", "multiedit", "replace", "replace_all"];
const CAPTURE_MULTI_EDIT_TOOLS = ["multi_edit", "multiedit", "replace_all"];
const CAPTURE_PATH_KEYS = ["file_path", "filePath", "path", "absolute_path", "AbsolutePath", "notebook_path"];
function captureCallId(payload: Record<string, unknown>): string | undefined {
  return CAPTURE_CALL_ID_KEYS.map((k) => payload[k]).find((v): v is string => typeof v === "string" && /^[A-Za-z0-9_.-]{1,128}$/.test(v));
}
// Any present path field of the wrong type rejects the whole entry.
function captureDirectPaths(o: any): string[] | undefined {
  if (!o || typeof o !== "object") return undefined;
  const r: string[] = [];
  for (const k of CAPTURE_PATH_KEYS) {
    if (!(k in o)) continue;
    if (typeof o[k] !== "string") return undefined;
    r.push(o[k]);
  }
  if ("paths" in o) {
    if (!Array.isArray(o.paths)) return undefined;
    if (o.paths.some((x: unknown) => typeof x !== "string")) return undefined;
    r.push(...o.paths);
  }
  if (!r.length) return undefined;
  return r.length <= CAPTURE_MAX_CANDIDATES ? r : undefined;
}
function captureMultiEditPaths(args: Record<string, unknown> | undefined, direct: string[] | undefined): string[] | undefined {
  const entries = args?.edits ?? args?.replacements;
  if (!Array.isArray(entries)) return undefined;
  if (!entries.length || entries.length > CAPTURE_MAX_CANDIDATES) return undefined;
  const paths = direct ?? [];
  for (const entry of entries) {
    const more = captureDirectPaths(entry);
    if (!more) return undefined;
    if (paths.length + more.length > CAPTURE_MAX_CANDIDATES) return undefined;
    paths.push(...more);
  }
  return paths;
}
function captureTool(payload: Record<string, unknown>): CaptureToolInfo {
  const name = typeof payload.tool === "string" ? payload.tool.toLowerCase() : "";
  const args = payload.args as Record<string, unknown> | undefined;
  const callID = captureCallId(payload);
  if (CAPTURE_SEARCH_TOOLS.includes(name)) return { family: "search-list", extraction: "not-applicable", callID };
  if (CAPTURE_NON_FILE_TOOLS.includes(name)) return { family: "non-file", extraction: "extracted", callID };
  if (!CAPTURE_FILE_TOOLS.includes(name)) return { family: "unknown", extraction: "extracted", callID };
  let paths = captureDirectPaths(args);
  if (CAPTURE_MULTI_EDIT_TOOLS.includes(name)) paths = captureMultiEditPaths(args, paths);
  const malformed = !paths || paths.some((p) => !p.trim() || [...p].length > CAPTURE_MAX_PATH_CHARS);
  if (malformed) return { family: "file", extraction: "missing-or-malformed", callID };
  return { family: "file", paths, extraction: "extracted", callID };
}
function captureMatchPattern(candidate: { path: string; windows: boolean }, pattern: CaptureConfig["patterns"][number], budget: { work: number }): CaptureDisposition | undefined {
  if (candidate.windows !== pattern.windows) return undefined;
  if (pattern.directory && captureGlob(pattern.directory, candidate.path, pattern.windows, budget)) return "drop";
  const match = captureGlob(pattern.path, candidate.path, pattern.windows, budget);
  if (match === undefined) return "metadata-only";
  return match ? "drop" : undefined;
}
// Any match drops; an exhausted match budget fails closed to metadata-only for that candidate.
function captureFileDisposition(paths: string[], config: CaptureConfig): CaptureDisposition {
  const candidates = paths.map((p) => captureNormalize(/^(?:\/|\\\\|[A-Za-z]:[\\/])/.test(p) ? p : captureJoin(config.base, p)));
  if (candidates.some((p) => !p)) return "metadata-only";
  const budget = { work: 0 };
  let disposition: CaptureDisposition = "keep";
  for (const candidate of candidates as { path: string; windows: boolean }[]) {
    for (const pattern of config.patterns) {
      const result = captureMatchPattern(candidate, pattern, budget);
      if (result === "drop") return "drop";
      if (result === "metadata-only") { disposition = result; break; }
    }
  }
  return disposition;
}
function captureDisposition(config: CaptureConfig, tool: CaptureToolInfo): CaptureDisposition {
  if (config.state === "invalid") return tool.family === "file" ? "metadata-only" : "keep";
  if (config.state !== "active") return "keep";
  if (tool.family === "search-list") return "drop";
  if (tool.family !== "file") return "keep";
  if (!tool.paths) return "metadata-only";
  return captureFileDisposition(tool.paths, config);
}
function captureMetadataPayload(payload: Record<string, unknown>, cwd: string | undefined, tool: CaptureToolInfo, protocol: CaptureProtocol): Record<string, unknown> {
  const session = payload.sessionID ?? payload.sessionId ?? payload.session_id;
  const routing = typeof payload.cwd === "string" ? payload.cwd : cwd;
  return { ...(typeof session === "string" ? { session_id: session } : {}), ...(typeof routing === "string" ? { cwd: routing } : {}), tool_family: tool.family, tool_name: tool.family, ...(tool.callID ? { tool_call_id: tool.callID } : {}), _ai_memory_capture: protocol };
}
function capturePolicy(payload: Record<string, unknown>, cwd: string | undefined): { disposition: CaptureDisposition; protocol?: CaptureProtocol; payload: Record<string, unknown> } {
  const config = captureConfig(cwd);
  const tool = captureTool(payload);
  const disposition = captureDisposition(config, tool);
  if (config.state === "inactive") return { disposition, payload };
  const protocol: CaptureProtocol = { version: CAPTURE_POLICY_V1, disposition, policy_state: config.state, tool_family: tool.family, path_count: tool.paths?.length ?? 0, extraction_state: tool.extraction };
  if (disposition === "metadata-only") return { disposition, protocol, payload: captureMetadataPayload(payload, cwd, tool, protocol) };
  if (disposition === "keep") return { disposition, protocol, payload: { ...payload, _ai_memory_capture: protocol } };
  return { disposition, protocol, payload };
}


function timeoutSignal(ms: number): AbortSignal | undefined {
  if (typeof AbortSignal === "undefined") return undefined;
  const timeoutFn = (AbortSignal as unknown as { timeout?: (ms: number) => AbortSignal }).timeout;
  return timeoutFn ? timeoutFn(ms) : undefined;
}

function authHeaders(): Record<string, string> {
  const token = resolveToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

const HOOK_QUEUE_MAX = 100;
const HOOK_FLUSH_INTERVAL_MS = 2000;
const HOOK_FLUSH_THRESHOLD = 20;
const HOOK_INTER_REQUEST_DELAY_MS = 50;
const HOOK_REQUEST_TIMEOUT_MS = 2000;
const HOOK_IMMEDIATE_EVENTS = new Set(["session-start", "stop", "session-end", "pre-compact"]);

type HookQueueItem = { event: string; url: URL; payload: Record<string, unknown> };
const hookQueue: HookQueueItem[] = [];
let hookFlushTimer: ReturnType<typeof setTimeout> | undefined;
let hookDraining = false;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function scheduleHookFlush(): void {
  if (hookFlushTimer) return;
  hookFlushTimer = setTimeout(() => {
    hookFlushTimer = undefined;
    void drainHookQueue();
  }, HOOK_FLUSH_INTERVAL_MS);
  hookFlushTimer.unref?.();
}


// Resolve the server bearer per request. A statically embedded token wins
// (inline installs), then the environment, then the 0600 auth-token file
// that `install-hooks --apply` persists under the data dir (#552).
function resolveToken(): string | null {
  if (TOKEN) return TOKEN;
  const envToken = process.env.AI_MEMORY_AUTH_TOKEN;
  if (envToken && envToken.trim()) return envToken.trim();
  try {
    const dataDir = process.env.AI_MEMORY_DATA_DIR?.trim();
    const base = dataDir
      ? dataDir
      : process.platform === "darwin"
        ? join(homedir(), "Library", "Application Support", "ai-memory")
        : process.platform === "win32"
          ? join(process.env.LOCALAPPDATA ?? join(homedir(), "AppData", "Local"), "ai-memory")
          : join(process.env.XDG_DATA_HOME?.trim() || join(homedir(), ".local", "share"), "ai-memory");
    const tokenPath = join(base, "auth-token");
    if (existsSync(tokenPath)) {
      const fromFile = readMarkerText(tokenPath, "utf-8").trim();
      if (fromFile) return fromFile;
    }
  } catch {
    // Best effort: an unreadable token file leaves auth absent.
  }
  return null;
}

// ---- offline spool (#580): the same on-disk contract as `ai-memory hook` ----
// <data_dir>/hook-spool, entries the CLI's hook-drain understands. Written on
// delivery failure, drained here on first use and after each queue flush; the
// ingest_key minted at spool time makes a double drain idempotent server-side.
function hookSpoolDir(): string {
  const env = process.env.AI_MEMORY_DATA_DIR;
  if (env && env.trim()) return join(env, "hook-spool");
  const home = homedir();
  const base =
    process.platform === "darwin"
      ? join(home, "Library", "Application Support", "ai-memory")
      : process.platform === "win32"
        ? join(process.env.LOCALAPPDATA ?? join(home, "AppData", "Local"), "ai-memory")
        : join(process.env.XDG_DATA_HOME?.trim() || join(home, ".local", "share"), "ai-memory");
  return join(base, "hook-spool");
}

let spoolSeq = 0;

function spoolFailedHook(url: URL | string, payload: Record<string, unknown>): void {
  try {
    const dir = hookSpoolDir();
    mkdirSync(dir, { recursive: true, mode: 0o700 });
    const createdMs = Date.now();
    // Idempotency key minted ONCE at spool time and baked into the URL,
    // so this plugin's drain and the CLI's drain can both deliver the
    // entry without double-ingesting.
    const key = `ts${createdMs.toString(16)}${Math.floor(Math.random() * 0xffffffff).toString(16)}`;
    const u = new URL(String(url));
    if (!u.searchParams.has("ingest_key")) u.searchParams.set("ingest_key", key);
    const token = resolveToken();
    const entry = {
      url: u.toString(),
      body: JSON.stringify(payload),
      created_ms: createdMs,
      auth_mode: token ? "static" : "none",
      ...(token ? { token } : {}),
      attempts: 0,
    };
    const seq = (spoolSeq++ & 0xffffffff).toString(16).padStart(16, "0");
    const name = `${String(createdMs).padStart(13, "0")}-${process.pid}-${seq}.json`;
    const tmp = join(dir, `${name}.tmp`);
    writeFileSync(tmp, JSON.stringify(entry), { mode: 0o600 });
    renameSync(tmp, join(dir, name));
  } catch (_e) {
    // Spooling is best-effort on top of best-effort capture.
  }
}

let spoolDrainPromise: Promise<void> | undefined;

function requestSpoolDrain(): void {
  if (spoolDrainPromise) return;
  spoolDrainPromise = drainHookSpool().finally(() => {
    spoolDrainPromise = undefined;
  });
}

async function drainHookSpool(): Promise<void> {
  let names: string[];
  try {
    names = readdirSync(hookSpoolDir()).filter((n) => n.endsWith(".json"));
  } catch (_e) {
    return; // no spool dir = nothing queued
  }
  names.sort();
  for (const name of names.slice(0, 500)) {
    const file = join(hookSpoolDir(), name);
    let entry: { url?: string; body?: string; token?: string };
    try {
      entry = JSON.parse(readMarkerText(file, "utf8"));
    } catch (_e) {
      continue; // torn or foreign file; leave it for the CLI drain
    }
    if (!entry.url || typeof entry.body !== "string") continue;
    try {
      const headers: Record<string, string> = { "Content-Type": "application/json" };
      if (entry.token) headers["Authorization"] = `Bearer ${entry.token}`;
      const resp = await fetch(entry.url, {
        method: "POST",
        headers,
        body: entry.body,
        signal: timeoutSignal(2000),
      }).catch(() => undefined);
      if (!resp) return; // still unreachable; stop, keep the backlog
      if (resp.ok || (resp.status >= 400 && resp.status < 500)) {
        // Delivered, or permanently rejected - either way, done with it.
        try { unlinkSync(file); } catch (_e) {}
      } else {
        return; // 5xx: server unhappy; retry a later drain
      }
    } catch (_e) {
      return;
    }
    await new Promise<void>((r) => setTimeout(r, 50));
  }
}

function enqueueHook(event: string, url: URL, payload: Record<string, unknown>): void {
  if (hookQueue.length >= HOOK_QUEUE_MAX) hookQueue.shift();
  hookQueue.push({ event, url, payload });
  if (HOOK_IMMEDIATE_EVENTS.has(event) || hookQueue.length >= HOOK_FLUSH_THRESHOLD) {
    void drainHookQueue();
  } else {
    scheduleHookFlush();
  }
}

async function drainHookQueue(): Promise<void> {
  if (hookDraining) return;
  requestSpoolDrain();
  hookDraining = true;
  if (hookFlushTimer) {
    clearTimeout(hookFlushTimer);
    hookFlushTimer = undefined;
  }
  try {
    while (hookQueue.length > 0) {
      const item = hookQueue.shift();
      if (!item) break;
      try {
        const resp = await fetch(item.url, {
          method: "POST",
          headers: { "Content-Type": "application/json", ...authHeaders() },
          body: JSON.stringify(item.payload),
          signal: timeoutSignal(HOOK_REQUEST_TIMEOUT_MS),
        }).catch(() => undefined);
        // Unreachable server or 5xx: keep the event on disk for a later
        // drain (#580). 4xx is permanent - spooling it would retry a
        // rejection forever.
        if (!resp || resp.status >= 500) spoolFailedHook(item.url, item.payload);
      } catch (_e) {
        try { spoolFailedHook(item.url, item.payload); } catch (_e2) {}
      }
      if (hookQueue.length > 0) await sleep(HOOK_INTER_REQUEST_DELAY_MS);
    }
  } finally {
    hookDraining = false;
    if (hookQueue.length > 0) void drainHookQueue();
  }
}

// Marker search stops at home for paths under it, otherwise at the enclosing
// git root, or at the start directory when neither applies.
function markerBoundary(dir: string, home: string): string | undefined {
  if (!home) return undefined;
  if (dir === home || dir.startsWith(home.endsWith(sep) ? home : home + sep)) return home;
  let probe = dir;
  while (probe && probe !== dirname(probe)) {
    if (existsSync(join(probe, ".git"))) return probe;
    probe = dirname(probe);
  }
  return dir;
}

function findMarker(cwd: string | undefined): string | undefined {
  if (!cwd) return undefined;
  let dir = resolve(cwd);
  const boundary = markerBoundary(dir, homedir());
  while (dir && dir !== dirname(dir)) {
    const marker = join(dir, ".ai-memory.toml");
    if (existsSync(marker)) return marker;
    if (boundary && dir === boundary) return undefined;
    dir = dirname(dir);
  }
  return undefined;
}

function tomlKey(text: string, key: string): string | undefined {
  const re = new RegExp(`^\\s*${key}\\s*=\\s*"([^"]*)"`);
  for (const line of text.split(/\r?\n/)) {
    const match = re.exec(line);
    if (match) return match[1];
  }
  return undefined;
}


function repoRootProject(cwd: string | undefined): string | undefined {
  if (!cwd) return undefined;
  try {
    const inside = execFileSync("git", ["-C", cwd, "rev-parse", "--is-inside-work-tree"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (inside !== "true") return undefined;
    const common = execFileSync("git", ["-C", cwd, "rev-parse", "--path-format=absolute", "--git-common-dir"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!common) return undefined;
    const root = dirname(common);
    if (!root || root === dirname(root)) return undefined;
    return basename(root);
  } catch (_e) {
    return undefined;
  }
}
function tomlFlag(text: string, key: string): string | undefined {
  const re = new RegExp(`^\\s*${key}\\s*=\\s*(?:"([^"]*)"|([^#\\s]+))`);
  for (const line of text.split(/\r?\n/)) {
    const match = re.exec(line);
    if (match) return match[1] ?? match[2];
  }
  return undefined;
}
// [marker key, query param] in query order; quoted keys use tomlKey, flags use tomlFlag.
const MARKER_KEY_PARAMS = [["workspace", "workspace"], ["project", "project"], ["project_strategy", "project_strategy"], ["drop_subagent_captures", "drop_subagent"]];
const MARKER_FLAG_PARAMS = [["default_global", "default_global"], ["inject_on_session_start", "briefing"], ["max_chars", "briefing_budget"]];

function applyMarkerBody(url: URL, body: string, cwd: string): void {
  for (const [key, param] of MARKER_KEY_PARAMS) {
    const value = tomlKey(body, key);
    if (value) url.searchParams.set(param, value);
  }
  for (const [key, param] of MARKER_FLAG_PARAMS) {
    const value = tomlFlag(body, key);
    if (value) url.searchParams.set(param, value);
  }
  if (tomlKey(body, "project")) return;
  const projectStrategy = tomlKey(body, "project_strategy");
  if (projectStrategy !== "repo-root" && projectStrategy !== "repo_root") return;
  const repoProject = repoRootProject(cwd);
  if (repoProject) url.searchParams.set("project", repoProject);
}

function applyMarkerParams(url: URL, cwd: string | undefined): void {
  const managedRun = process.env.AI_MEMORY_RUN_ID;
  if (managedRun) url.searchParams.set("managed_run", managedRun);
  const marker = findMarker(cwd);
  if (!marker || !cwd) return;
  url.searchParams.set("cwd", cwd);
  try {
    applyMarkerBody(url, readFileSync(marker, "utf8"), cwd);
  } catch (_e) {
  }
}

function sessionID(ctx: any): string | undefined {
  const id = ctx?.sessionManager?.getSessionId?.();
  return typeof id === "string" && id.length > 0 ? id : undefined;
}

function modelName(model: any): string | undefined {
  const name = model?.id ?? model?.name ?? model?.model;
  return typeof name === "string" && name.length > 0 ? name : undefined;
}

function sessionPayload(ctx: any): Record<string, unknown> {
  return {
    sessionID: sessionID(ctx),
    cwd: ctx?.cwd,
    model: modelName(ctx?.model),
  };
}

function stringify(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch (_e) {
    return String(value);
  }
}

function contentToText(content: unknown): string {
  if (content === null || content === undefined) return "";
  if (!Array.isArray(content)) return stringify(content);
  return content
    .map((part: any) => {
      if (typeof part?.text === "string") return part.text;
      if (typeof part?.content === "string") return part.content;
      if (typeof part?.type === "string") return `[${part.type}]`;
      return stringify(part);
    })
    .filter(Boolean)
    .join("\n\n")
    .trim();
}

const startedSessions = new Set<string>();
const handoffChecked = new Set<string>();
const preCompactLast = new Map<string, number>();

function startSession(ctx: any, extra: Record<string, unknown> = {}): void {
  const id = sessionID(ctx);
  if (!id || startedSessions.has(id)) return;
  startedSessions.add(id);
  // Generated integrations inject through fetchHandoff below. In managed mode
  // a queued SessionStart response is not model-visible and must not consume
  // the workstream context before that synchronous fetch receives it.
  if (!process.env.AI_MEMORY_RUN_ID) {
    postHook("session-start", { ...sessionPayload(ctx), ...extra });
  }
}

function postPreCompact(ctx: any): void {
  startSession(ctx);
  const key = sessionID(ctx) || "unknown";
  const now = Date.now();
  const last = preCompactLast.get(key) ?? 0;
  if (now - last < 1000) return;
  preCompactLast.set(key, now);
  postHook("pre-compact", sessionPayload(ctx));
}

function postHook(event: string, payload: Record<string, unknown>): void {
  const url = new URL(`${SERVER}/hook`);
  url.searchParams.set("event", event);
  url.searchParams.set("agent", AGENT);
  applyMarkerParams(url, typeof payload.cwd === "string" ? payload.cwd : undefined);
  const policy = capturePolicy(payload, typeof payload.cwd === "string" ? payload.cwd : undefined);
  if (policy.disposition === "drop") return;
  try {
    enqueueHook(event, url, policy.payload);
  } catch (_e) {
    // Best-effort capture. Hooks must never block the agent.
  }
}

async function fetchHandoff(cwd: string, id: string | undefined): Promise<string | undefined> {
  const url = new URL(`${SERVER}/handoff`);
  url.searchParams.set("agent", AGENT);
  url.searchParams.set("cwd", cwd);
  if (id) url.searchParams.set("session_id", id);
  applyMarkerParams(url, cwd);
  try {
    const response = await fetch(url, {
      headers: authHeaders(),
      signal: timeoutSignal(1000),
    });
    if (!response.ok) return undefined;
    const text = (await response.text()).trim();
    return text.length > 0 ? text : undefined;
  } catch (_e) {
    return undefined;
  }
}


// ---- MCP bridge ------------------------------------------------------------
const MCP_SERVER = deriveMcpServer(SERVER);
const MCP_REQUEST_TIMEOUT_MS = 10000;
let mcpRequestId = 0;

function deriveMcpServer(server: string): string {
  const trimmed = server.replace(/\/+$/, "");
  return trimmed.endsWith("/mcp") ? trimmed : `${trimmed}/mcp`;
}

function mcpSessionId(ctx: any): string | undefined {
  const id = sessionID(ctx) ?? ctx?.sessionId ?? ctx?.sessionID ?? ctx?.session?.id;
  return typeof id === "string" && id.length > 0 ? id : undefined;
}

function mcpSignal(signal?: AbortSignal): AbortSignal | undefined {
  const timeout = timeoutSignal(MCP_REQUEST_TIMEOUT_MS);
  if (!signal) return timeout;
  if (!timeout) return signal;
  const anyFactory = (AbortSignal as unknown as { any?: (signals: AbortSignal[]) => AbortSignal }).any;
  return anyFactory ? anyFactory([signal, timeout]) : timeout;
}

async function mcpRpc(method: string, params?: unknown, ctx?: any, signal?: AbortSignal): Promise<any> {
  const id = ++mcpRequestId;
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "Accept": "application/json, text/event-stream",
    ...authHeaders(),
  };
  const session = mcpSessionId(ctx);
  if (session) {
    headers["X-Memory-Actor-Session-Id"] = session;
    headers["Mcp-Session-Id"] = session;
  }
  const response = await fetch(MCP_SERVER, {
    method: "POST",
    headers,
    body: JSON.stringify({ jsonrpc: "2.0", id, method, params: params ?? {} }),
    signal: mcpSignal(signal),
  });
  if (!response.ok) throw new Error(`ai-memory MCP ${method} failed: HTTP ${response.status}`);
  const payload = await response.json();
  if (payload?.error) throw new Error(`ai-memory MCP ${method} failed: ${payload.error.message ?? JSON.stringify(payload.error)}`);
  if (payload?.result?.isError) throw new Error(`ai-memory MCP ${method} returned isError`);
  return payload?.result;
}

function toolInputSchema(tool: any): any {
  return tool?.inputSchema ?? { type: "object", additionalProperties: true };
}

async function bootstrapMcpBridge(pi: any): Promise<void> {
  try {
    await mcpRpc("initialize", {
      protocolVersion: "2025-03-26",
      capabilities: {},
      clientInfo: { name: "ai-memory-pi-extension", version: "0.0.0" },
    });
    try { await mcpRpc("notifications/initialized"); } catch (_e) {}
    const listed = await mcpRpc("tools/list");
    for (const tool of listed?.tools ?? []) {
      try {
        pi.registerTool({
          name: tool.name,
          label: tool.name,
          description: tool.description,
          parameters: toolInputSchema(tool),
          execute: async (_toolCallId: string, params: unknown, signal?: AbortSignal, _onUpdate?: unknown, ctx?: any) => {
            const result = await mcpRpc("tools/call", { name: tool.name, arguments: params ?? {} }, ctx, signal);
            return { content: result?.content ?? [], details: result };
          },
        });
      } catch (_e) {
        // Duplicate registration or tool-shape mismatch must not break lifecycle capture.
      }
    }
  } catch (_e) {
    // MCP bridge is best-effort; extension load and lifecycle capture must survive.
  }
}

export default function AiMemoryExtension(pi: any): void {
  try { void bootstrapMcpBridge(pi); } catch (_e) {}
  pi.on("session_start", (_event: any, ctx: any) => {
    startSession(ctx);
  });

  pi.on("before_agent_start", async (event: any, ctx: any) => {
    startSession(ctx);
    postHook("user-prompt", {
      ...sessionPayload(ctx),
      prompt: event?.prompt,
      imageCount: Array.isArray(event?.images) ? event.images.length : undefined,
    });

    const id = sessionID(ctx);
    if (!id || handoffChecked.has(id)) return;
    handoffChecked.add(id);
    const handoff = await fetchHandoff(ctx?.cwd ?? "", id);
    if (!handoff) return;
    return {
      message: {
        customType: "ai-memory-handoff",
        content: handoff,
        display: false,
        attribution: "agent",
      },
    };
  });

  pi.on("tool_call", (event: any, ctx: any) => {
    startSession(ctx);
    postHook("pre-tool-use", {
      ...sessionPayload(ctx),
      tool: event?.toolName,
      callID: event?.toolCallId,
      args: event?.input,
    });
  });

  pi.on("tool_result", (event: any, ctx: any) => {
    startSession(ctx);
    postHook("post-tool-use", {
      ...sessionPayload(ctx),
      tool: event?.toolName,
      callID: event?.toolCallId,
      args: event?.input,
      output: contentToText(event?.content),
      details: event?.details,
      isError: event?.isError,
    });
  });

  pi.on("session_before_compact", (_event: any, ctx: any) => {
    postPreCompact(ctx);
  });

  pi.on("session_compact", (_event: any, ctx: any) => {
    postPreCompact(ctx);
  });


  pi.on("agent_end", (_event: any, ctx: any) => {
    startSession(ctx);
    postHook("stop", sessionPayload(ctx));
  });

  pi.on("session_shutdown", (_event: any, ctx: any) => {
    startSession(ctx);
    postHook("session-end", sessionPayload(ctx));
  });
}
